[package]
name = "y2j"
version = "0.2.0"
authors = ["Rob Young <rob@robyoung.digital>"]
edition = "2018"

[dependencies]
serde = "1.0.119"
serde_yaml = "0.8.15"
serde_json = "1.0.61"

clap = "2.33"
anyhow = "1.0"
