# A lot of this is lifted from https://github.com/BurntSushi/ripgrep/blob/master/.github/workflows/release.yml
name: Release

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest

    outputs:
      version: ${{ steps.vars.outputs.version }}
      upload_url: ${{ steps.release.outputs.upload_url }}

    steps:
      - name: Release vars
        id: vars
        run: |
          version=${GITHUB_REF#refs/tags/}
          echo ::set-output name=version::${version}

      - name: Create GitHub release
        id: release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.vars.outputs.version }}
          release_name: ${{ steps.vars.outputs.version }}

  build:
    name: Build Binary
    runs-on: ${{ matrix.os }}

    needs: [release]

    strategy:
      matrix:
        include:
        - build: linux
          os: ubuntu-latest
          target: x86_64-unknown-linux-musl

        - build: linux-arm
          os: ubuntu-latest
          target: arm-unknown-linux-musleabihf

        - build: macos
          os: macos-latest
          target: x86_64-apple-darwin

        - build: win-msvc
          os: windows-2019
          target: x86_64-pc-windows-msvc

    steps:
      - uses: actions/checkout@v2

      - name: Install packages (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends musl-tools

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal
          override: true
          target: ${{ matrix.target }}

      - name: Install Cross
        run: |
          cargo install cross

      - name: Build release binary
        run: |
          cross build --release --target ${{ matrix.target }}
          ls -R

      - name: Strip release binary (linux and macos)
        if: matrix.build == 'linux' || matrix.build == 'macos'
        run: strip "target/${{ matrix.target }}/release/y2j"

      - name: Strip release binary (arm)
        if: matrix.build == 'linux-arm'
        run: |
          docker run --rm \
            -v "${PWD}/target:/target:Z" \
            rustembedded/cross:arm-unknown-linux-musleabihf \
            arm-linux-musleabihf-strip \
            /target/arm-unknown-linux-musleabihf/release/y2j

      - name: Release vars
        id: vars
        shell: bash
        run: |
          version=${{needs.release.outputs.version}}
          if [[ "${{ matrix.os }}" == "windows-2019" ]]; then
            suffix='.exe'
          else
            suffix=''
          fi
          echo ::set-output name=RELEASE_BINARY::target/${{ matrix.target }}/release/y2j${suffix}
          echo ::set-output name=ARTIFACT_NAME::y2j-${version}-${{ matrix.target }}${suffix}

      - name: Upload release binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.release.outputs.upload_url }}
          asset_path: ${{ steps.vars.outputs.RELEASE_BINARY }}
          asset_name: ${{ steps.vars.outputs.ARTIFACT_NAME }}
          asset_content_type: application/octet-stream
